In [1]:
from sklearn import feature_extraction
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

In [4]:
import jieba

In [5]:
corpus = "PDD从直播之后，个人技术呈直线上升，作为曾经的顶级上单，PDD在峡谷之巅钻石局混的如鱼得水，各种单杀更是亮眼，这局的PDD祭出了凯南，通过强攻天赋轻松单杀了对线的吸血鬼，正在PDD自我陶醉之际，队友之间却开始互喷了，原因仅仅只男枪被抢了镀层！PDD复出之后人气火爆，虽然直播效果不算特别好，但因为PDD的性格耿直、大方，不少观众都会到PDD直播间捧场。近日，PDD在直播中被队友挂机，不仅如此，队友还主动打字嘲讽，PDD一气之下直接联系拳头将队友永封！PDD：敢挂我机，你号没了！"




In [6]:
words = jieba.cut(corpus)


In [17]:
words= " ".join(words)

In [18]:
str1 = words

In [19]:
words = words.split(" ")

In [20]:
sentences = []

for i in range(len(words)//10 + 1):
    start = i*10
    end = min(start+10,len(words))
    sentence = words[start:end]
    sentences.append(sentence)

In [21]:
sentences

[['PDD', '从', '直播', '之后', '，', '个人', '技术', '呈', '直线', '上升'],
 ['，', '作为', '曾经', '的', '顶级', '上单', '，', 'PDD', '在', '峡谷'],
 ['之巅', '钻石', '局混', '的', '如鱼得水', '，', '各种', '单杀', '更是', '亮眼'],
 ['，', '这局', '的', 'PDD', '祭出', '了', '凯南', '，', '通过', '强攻'],
 ['天赋', '轻松', '单杀', '了', '对线', '的', '吸血鬼', '，', '正在', 'PDD'],
 ['自我陶醉', '之际', '，', '队友', '之间', '却', '开始', '互喷', '了', '，'],
 ['原因', '仅仅', '只', '男枪', '被', '抢', '了', '镀层', '！', 'PDD'],
 ['复出', '之后', '人气', '火爆', '，', '虽然', '直播', '效果', '不算', '特别'],
 ['好', '，', '但', '因为', 'PDD', '的', '性格', '耿直', '、', '大方'],
 ['，', '不少', '观众', '都', '会', '到', 'PDD', '直播间', '捧场', '。'],
 ['近日', '，', 'PDD', '在', '直播', '中', '被', '队友', '挂机', '，'],
 ['不仅如此', '，', '队友', '还', '主动', '打字', '嘲讽', '，', 'PDD', '一气之下'],
 ['直接', '联系', '拳头', '将', '队友', '永封', '！', 'PDD', '：', '敢'],
 ['挂', '我机', '，', '你', '号', '没', '了', '！']]

In [25]:
corpus = ['aaa ccc aaa aaa', 
          'aaa aaa', 
          'aaa aaa aaa', 
          'aaa aaa aaa aaa',
          'aaa bbb aaa bbb aaa',
          'ccc aaa aaa ccc aaa'
         ]


In [26]:
vectorizer = CountVectorizer()
x = vectorizer.fit_transform(corpus)

In [27]:
word = vectorizer.get_feature_names()  
print(word) 

['aaa', 'bbb', 'ccc']


In [29]:
counts =  x.toarray()
print (counts)

[[3 0 1]
 [2 0 0]
 [3 0 0]
 [4 0 0]
 [3 2 0]
 [3 0 2]]


In [30]:
transformer = TfidfTransformer()

In [32]:
tfidf = transformer.fit_transform(x)

In [39]:
a = tfidf.toarray()

In [40]:
import numpy as np

In [49]:
np.linalg.norm([3,4])

5.0

In [41]:
#compute cosin similarity 
def cos(x,y):
    x = np.mat(x)
    y = np.mat(y)
    num = np.dot(x,y)
    denom = np.linalg.norm(x) * np.linalg.norm(y)
    cos = num / denom
    return cos

In [42]:
print(a)

[[0.85151335 0.         0.52433293]
 [1.         0.         0.        ]
 [1.         0.         0.        ]
 [1.         0.         0.        ]
 [0.55422893 0.83236428 0.        ]
 [0.63035731 0.         0.77630514]]


In [43]:
cos(a[1],a[2])

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)